env:
  browser: true
  es2021: true
extends:
  - 'standard-with-typescript'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: './tsconfig.json'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/semi': [error, always]
  '@typescript-eslint/no-misused-promises': [error, { checksVoidReturn: false }]
  '@typescript-eslint/no-floating-promises': [error, { ignoreIIFE: true }]
  'no-console': [error, { allow: ["error"] }]
  semi: [error, always]
