env:
    browser: true
    es6: true
    jquery: true
extends: standard
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
    sourceType: module
rules:
    indent:
        - error
        - 4
    semi:
        - error
        - always
    sort-keys:
        - error
    valid-jsdoc:
        - error
