language: php
sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.3
          env: deps="low"
        - php: 7.3
          env: deps="high"

install:
    - composer install --no-interaction --no-dev

